<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>BeamNG Log</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>^.*?\|</string>
            <key>name</key>
            <string>variable.function.parameter.js</string>
            <key>comment</key>
            <string>Line Beginning</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^--.*$</string>
            <key>name</key>
            <string>comment.line.double-slash.js</string>
            <key>comment</key>
            <string>Comment</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(A|I)[|]([^|]+)[|](.*)$</string>
            <key>name</key>
            <string>string.quoted.single.js</string>
            <key>comment</key>
            <string>Info</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(D)[|]([^|]+)[|](.*)$</string>
            <key>name</key>
            <string>entity.name.function.js</string>
            <key>comment</key>
            <string>Debug</string>
        </dict>
        <dict>
            <key>match</key>
            <string>[E][|]([^|]+)[|](.*)$</string>
            <key>name</key>
            <string>support.constant.dom.js</string>
            <key>comment</key>
            <string>Error</string>
        </dict>
        <dict>
            <key>match</key>
            <string>[W][|]([^|]+)[|](.*)$</string>
            <key>name</key>
            <string>storage.type.function.js</string>
            <key>comment</key>
            <string>Warning</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>text.beamng</string>
    <key>uuid</key>
    <string>5fb77f58-2721-11e5-b345-feff819cdc9f</string>
</dict>
</plist>
